### ISSUE TITLE
Imexam Overview notebook - a.grab() returns an error

### ISSUE THREAD

**Issue by akalyaan** [spacetelescope/aas229_workshop#18]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-87f6e506a62b> in <module>()
----> 1 a.grab() # Optional if you want to save a view in the notebook for reference, if using the notebook backend
      2 
      3 # as seen below, if you are displaying images outside the notebook, they will be saved to file.

/Users/anusha/astroconda/envs/aas229-workshop/lib/python3.5/site-packages/imexam/connect.py in grab(self)
    158     def grab(self):
    159         """Display a snapshop of the current image in the browser window."""
--> 160         return self.window.grab()
    161 
    162     def get_data_filename(self):

/Users/anusha/astroconda/envs/aas229-workshop/lib/python3.5/site-packages/imexam/ds9_viewer.py in grab(self)
   1687         """Make a copy of the image view."""
   1688         backend = get_backend().lower()
-> 1689         fname = self.snapsave(format="png")
   1690         if "nbagg" in backend:  # save inside the notebook
   1691                 data = mpimage.imread(fname)

/Users/anusha/astroconda/envs/aas229-workshop/lib/python3.5/site-packages/imexam/ds9_viewer.py in snapsave(self, filename, format, resolution)
   1679         # self.set(cstring)
   1680         # save the local directory, erase later?
-> 1681         call(cstring)
   1682         print("Image saved to {0:s}".format(filename))
   1683         logging.info("Image saved to {0:s}".format(filename))

/Users/anusha/astroconda/envs/aas229-workshop/lib/python3.5/subprocess.py in call(timeout, *popenargs, **kwargs)
    555     retcode = call(["ls", "-l"])
    556     """
--> 557     with Popen(*popenargs, **kwargs) as p:
    558         try:
    559             return p.wait(timeout=timeout)

/Users/anusha/astroconda/envs/aas229-workshop/lib/python3.5/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds)
    945                                 c2pread, c2pwrite,
    946                                 errread, errwrite,
--> 947                                 restore_signals, start_new_session)
    948         except:
    949             # Cleanup if the child failed starting.

/Users/anusha/astroconda/envs/aas229-workshop/lib/python3.5/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1549                             else:
   1550                                 err_msg += ': ' + repr(orig_executable)
-> 1551                     raise child_exception_type(errno_num, err_msg)
   1552                 raise child_exception_type(err_msg)
   1553 

FileNotFoundError: [Errno 2] No such file or directory: 'import'

**Comment by sosey** [comment]
"import" is the unix import command that imexam uses to grab a copy of the DS9 window, it's a fairly include standard for mac and linux os, it may not exist for windows machines. Try checking your path for import "which import". If it's not there, the next best way is to just save a screenshot of the window itself. The grab() function for DS9 is the only one that uses import to make a copy, this shouldn't affect the ginga windows or the plot saving.   

I switched to using import to get around a bug in the XPA for the saveimage call. The ‘SaveImage’ function basically does a screen capture. In the case of MacOSX (and XQuartz) and you are configured to be rootless, the screen capture fails if your DS9 window is not in the upper left corner of the primary screen - the call works if you are using a laptop that is not connected to a larger display, or a workstation with only one monitor. Since these are harder things to automatically grab from user machines,  the workaround was to  ‘Print’ to a file, generating a postscript image that can be rendered outside of ds9 (for example /Applications/Preview). However, I was unable to get this to save to file, it insisted on sending the image directly to the printer. This also makes for greater unknowns on user machines. 

The workarounds for users who hit this may be:

- grab a copy of the window yourself
- move the DS9 window to the appropriate screen and issue the saveimage command, assuming "a" is your control object:
```a.window.xpa.set("saveimage ds9.jpeg")```
    

See also https://github.com/spacetelescope/imexam/issues/91

**Comment by akalyaan** [comment]
Thanks Megan !! I will check it out !

On Jan 17, 2017 11:52 AM, "Megan Sosey" <notifications@github.com> wrote:

Closed #18 <https://github.com/spacetelescope/aas229_workshop/issues/18>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spacetelescope/aas229_workshop/issues/18#event-926290974>,
or mute the thread
